camunda:
  bpm:
    authorization:
      enabled: true
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks

okta:
  oauth2:
    issuer: https://dev-66748045.okta.com/oauth2/default
    client-id: xxx
    client-secret: xxx
    scopes: openid,profile,email
    groupsClaim: camunda-groups
    post-logout-redirect-uri: http://localhost:8080/camunda

